# Generated by Django 4.1.1 on 2023-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=200)),
                ("l_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("desc", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="home_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=200)),
                ("l_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("pnum", models.IntegerField()),
            ],
        ),
    ]
