# Generated by Django 4.1.1 on 2023-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.IntegerField(max_length=3)),
                ("month", models.CharField(max_length=20)),
                ("event", models.CharField(max_length=20)),
            ],
        ),
    ]
