# Generated by Django 4.1.1 on 2023-08-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0002_events"),
    ]

    operations = [
        migrations.RenameModel(old_name="events", new_name="event",),
    ]
