# Generated by Django 4.1.1 on 2023-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0004_event_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.ImageField(default="", upload_to="activity/images"),
                ),
            ],
        ),
        migrations.RemoveField(model_name="event", name="activity",),
        migrations.AddField(
            model_name="event",
            name="event_img",
            field=models.ImageField(default="", upload_to="event/images"),
        ),
    ]
