# Generated by Django 4.1.1 on 2023-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0005_activity_remove_event_activity_event_event_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_img",
            field=models.ImageField(default="", upload_to="activity/images"),
        ),
    ]
