# Generated by Django 4.1.1 on 2023-08-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0006_alter_event_event_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("notice", models.CharField(max_length=200)),
            ],
        ),
    ]
