# Generated by Django 4.1.1 on 2023-09-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0007_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="reigistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=50)),
                ("father_name", models.CharField(max_length=50)),
                ("mother_name", models.CharField(max_length=50)),
                ("dob", models.CharField(max_length=10)),
                ("phone_number", models.IntegerField(max_length=50)),
                ("email_id", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("class_for", models.CharField(max_length=50)),
                ("last_schl", models.CharField(max_length=80)),
                ("address", models.CharField(max_length=100)),
                ("trans_req", models.CharField(max_length=10)),
            ],
        ),
    ]
