# Generated by Django 4.1.1 on 2023-09-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0008_reigistration"),
    ]

    operations = [
        migrations.RenameModel(old_name="reigistration", new_name="registration",),
    ]
