# Generated by Django 4.1.1 on 2023-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0009_rename_reigistration_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assembly",
                    models.ImageField(default="", upload_to="activity/images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.ImageField(default="", upload_to="activity/images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="inaugration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inaugration",
                    models.ImageField(default="", upload_to="activity/images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pt", models.ImageField(default="", upload_to="activity/images")),
            ],
        ),
    ]
