# Generated by Django 4.2.6 on 2024-06-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_activity_created_at_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created_at',
        ),
    ]
