# Generated by Django 4.2.6 on 2024-06-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_notice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(default='', upload_to='events/images'),
        ),
    ]
