# Generated by Django 4.2.6 on 2024-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0017_alter_event_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(default='events/images', upload_to='events/images'),
        ),
    ]
