# Generated by Django 4.2.6 on 2024-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0018_alter_event_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(default='activity/images', upload_to='activity/images'),
        ),
    ]
