# Generated by Django 4.2.6 on 2024-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0019_alter_event_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(default='', upload_to='events/images'),
        ),
    ]
