# Generated by Django 4.2.6 on 2024-06-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0021_assembly_created_at_function_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='pnum',
        ),
    ]
