# Generated by Django 4.2.6 on 2024-06-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0022_rename_desc_contact_pnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home_form',
        ),
    ]
